[workspace]
resolver = "2"
members = [
    "packages/parser",
    "packages/codebase-parser",
    "packages/language-server",
]
exclude = [
		"packages/analyzer",
	  "sandbox/structural-programming"
]
