
[ModuleField]
name: Range
declaration: Node
- (name) Identifier + (declaration) [ModuleField::Declaration]

[ModuleField::Declaration]
- [Property]
- [Getter]
- [Function]

[Property]

[Getter]


[Literal]
value: Token
- (value) Identifier
- (value) Number
- (value) RawString
