[package]
name = "fa"
version = "0.1.0"
authors = ["Matthieu Gindre 'Gin Quin' <gin.the.quin@gmail.com>"]
edition = "2021"

[build-dependencies]
lalrpop = { version = "0.22.0" }

[dependencies]
lalrpop-util = { version = "0.22.0", features = ["lexer", "unicode"] }
