[package]
name = "fa-language-server-protocol"
version = "0.1.0"
authors = ["Matthieu Gindre 'Gin Quin' <gin.the.quin@gmail.com>"]
edition = "2024"

[dependencies]
tokio = { version = "1.43.0", features = ["full"] }
tower-lsp = "0.20.0"

