
let routes = {
	[[routes]]
	key = "deal_with_fds"
	path = "/"
	pattern = "^/((consult-fds|my-fds|my-safebox|my-chemical-base|my-tools|shopping-cart)(/.*)?)\$"

	[[routes]]
	key = "expert_tools"
	path = "/solutions"

	[routes.sub.info_send_proof]
	path = "/info-send-proof"
	text = "Preuves d'envoi"

	[routes.sub.info_push_and_proof]
	path = "/info-push-and-proof"
	text = "Module PUSH & PROOF"

	[routes.sub.info_quifds_witness]
	path = "/info-quickfds-witness"
	text = "Quick-FDS WITNESS"

	[routes.sub.info_safebox]
	path = "/info-safebox"
	text = "Programme SafeBox"

	[routes.sub.info_hosting]
	path = "/info-hosting"
	text = "Hébergement à valeur ajoutée"

	[[routes]]
	key = "consulting_and_formation"
	path = "/consulting"

	[[routes]]
	key = "news"
	path = "/news"

	[[routes]]
	key = "who_we_are"
	path = "/about-us"
}